// <auto-generated />
#pragma warning disable CS0649
using System.Runtime.InteropServices;

namespace StbSharp.Interop
{
    internal enum stbir_pixel_layout
    {
        STBIR_1CHANNEL = 1,
        STBIR_2CHANNEL = 2,
        STBIR_RGB = 3,
        STBIR_BGR = 0,
        STBIR_4CHANNEL = 5,
        STBIR_RGBA = 4,
        STBIR_BGRA = 6,
        STBIR_ARGB = 7,
        STBIR_ABGR = 8,
        STBIR_RA = 9,
        STBIR_AR = 10,
        STBIR_RGBA_PM = 11,
        STBIR_BGRA_PM = 12,
        STBIR_ARGB_PM = 13,
        STBIR_ABGR_PM = 14,
        STBIR_RA_PM = 15,
        STBIR_AR_PM = 16,
        STBIR_RGBA_NO_AW = 11,
        STBIR_BGRA_NO_AW = 12,
        STBIR_ARGB_NO_AW = 13,
        STBIR_ABGR_NO_AW = 14,
        STBIR_RA_NO_AW = 15,
        STBIR_AR_NO_AW = 16,
    }

    internal enum stbir_edge
    {
        STBIR_EDGE_CLAMP = 0,
        STBIR_EDGE_REFLECT = 1,
        STBIR_EDGE_WRAP = 2,
        STBIR_EDGE_ZERO = 3,
    }

    internal enum stbir_filter
    {
        STBIR_FILTER_DEFAULT = 0,
        STBIR_FILTER_BOX = 1,
        STBIR_FILTER_TRIANGLE = 2,
        STBIR_FILTER_CUBICBSPLINE = 3,
        STBIR_FILTER_CATMULLROM = 4,
        STBIR_FILTER_MITCHELL = 5,
        STBIR_FILTER_POINT_SAMPLE = 6,
        STBIR_FILTER_OTHER = 7,
    }

    internal enum stbir_datatype
    {
        STBIR_TYPE_UINT8 = 0,
        STBIR_TYPE_UINT8_SRGB = 1,
        STBIR_TYPE_UINT8_SRGB_ALPHA = 2,
        STBIR_TYPE_UINT16 = 3,
        STBIR_TYPE_FLOAT = 4,
        STBIR_TYPE_HALF_FLOAT = 5,
    }

    internal partial struct stbir__info
    {
    }

    internal unsafe partial struct STBIR_RESIZE
    {
        public void* user_data;

        [NativeTypeName("const void *")]
        public void* input_pixels;

        public int input_w;

        public int input_h;

        public double input_s0;

        public double input_t0;

        public double input_s1;

        public double input_t1;

        [NativeTypeName("stbir_input_callback *")]
        public delegate* unmanaged[Cdecl]<void*, void*, int, int, int, void*, void*> input_cb;

        public void* output_pixels;

        public int output_w;

        public int output_h;

        public int output_subx;

        public int output_suby;

        public int output_subw;

        public int output_subh;

        [NativeTypeName("stbir_output_callback *")]
        public delegate* unmanaged[Cdecl]<void*, int, int, void*, void> output_cb;

        public int input_stride_in_bytes;

        public int output_stride_in_bytes;

        public int splits;

        public int fast_alpha;

        public int needs_rebuild;

        public int called_alloc;

        public stbir_pixel_layout input_pixel_layout_public;

        public stbir_pixel_layout output_pixel_layout_public;

        public stbir_datatype input_data_type;

        public stbir_datatype output_data_type;

        public stbir_filter horizontal_filter;

        public stbir_filter vertical_filter;

        public stbir_edge horizontal_edge;

        public stbir_edge vertical_edge;

        [NativeTypeName("stbir__kernel_callback *")]
        public delegate* unmanaged[Cdecl]<float, float, void*, float> horizontal_filter_kernel;

        [NativeTypeName("stbir__support_callback *")]
        public delegate* unmanaged[Cdecl]<float, void*, float> horizontal_filter_support;

        [NativeTypeName("stbir__kernel_callback *")]
        public delegate* unmanaged[Cdecl]<float, float, void*, float> vertical_filter_kernel;

        [NativeTypeName("stbir__support_callback *")]
        public delegate* unmanaged[Cdecl]<float, void*, float> vertical_filter_support;

        public stbir__info* samplers;
    }

    internal static unsafe partial class StbImageResize2
    {
        [DllImport("stb_image", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        [return: NativeTypeName("unsigned char *")]
        public static extern byte* stbir_resize_uint8_srgb([NativeTypeName("const unsigned char *")] byte* input_pixels, int input_w, int input_h, int input_stride_in_bytes, [NativeTypeName("unsigned char *")] byte* output_pixels, int output_w, int output_h, int output_stride_in_bytes, stbir_pixel_layout pixel_type);

        [DllImport("stb_image", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        [return: NativeTypeName("unsigned char *")]
        public static extern byte* stbir_resize_uint8_linear([NativeTypeName("const unsigned char *")] byte* input_pixels, int input_w, int input_h, int input_stride_in_bytes, [NativeTypeName("unsigned char *")] byte* output_pixels, int output_w, int output_h, int output_stride_in_bytes, stbir_pixel_layout pixel_type);

        [DllImport("stb_image", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern float* stbir_resize_float_linear([NativeTypeName("const float *")] float* input_pixels, int input_w, int input_h, int input_stride_in_bytes, float* output_pixels, int output_w, int output_h, int output_stride_in_bytes, stbir_pixel_layout pixel_type);

        [DllImport("stb_image", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void* stbir_resize([NativeTypeName("const void *")] void* input_pixels, int input_w, int input_h, int input_stride_in_bytes, void* output_pixels, int output_w, int output_h, int output_stride_in_bytes, stbir_pixel_layout pixel_layout, stbir_datatype data_type, stbir_edge edge, stbir_filter filter);

        [DllImport("stb_image", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void stbir_resize_init(STBIR_RESIZE* resize, [NativeTypeName("const void *")] void* input_pixels, int input_w, int input_h, int input_stride_in_bytes, void* output_pixels, int output_w, int output_h, int output_stride_in_bytes, stbir_pixel_layout pixel_layout, stbir_datatype data_type);

        [DllImport("stb_image", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void stbir_set_datatypes(STBIR_RESIZE* resize, stbir_datatype input_type, stbir_datatype output_type);

        [DllImport("stb_image", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void stbir_set_pixel_callbacks(STBIR_RESIZE* resize, [NativeTypeName("stbir_input_callback *")] delegate* unmanaged[Cdecl]<void*, void*, int, int, int, void*, void*> input_cb, [NativeTypeName("stbir_output_callback *")] delegate* unmanaged[Cdecl]<void*, int, int, void*, void> output_cb);

        [DllImport("stb_image", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void stbir_set_user_data(STBIR_RESIZE* resize, void* user_data);

        [DllImport("stb_image", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void stbir_set_buffer_ptrs(STBIR_RESIZE* resize, [NativeTypeName("const void *")] void* input_pixels, int input_stride_in_bytes, void* output_pixels, int output_stride_in_bytes);

        [DllImport("stb_image", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int stbir_set_pixel_layouts(STBIR_RESIZE* resize, stbir_pixel_layout input_pixel_layout, stbir_pixel_layout output_pixel_layout);

        [DllImport("stb_image", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int stbir_set_edgemodes(STBIR_RESIZE* resize, stbir_edge horizontal_edge, stbir_edge vertical_edge);

        [DllImport("stb_image", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int stbir_set_filters(STBIR_RESIZE* resize, stbir_filter horizontal_filter, stbir_filter vertical_filter);

        [DllImport("stb_image", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int stbir_set_filter_callbacks(STBIR_RESIZE* resize, [NativeTypeName("stbir__kernel_callback *")] delegate* unmanaged[Cdecl]<float, float, void*, float> horizontal_filter, [NativeTypeName("stbir__support_callback *")] delegate* unmanaged[Cdecl]<float, void*, float> horizontal_support, [NativeTypeName("stbir__kernel_callback *")] delegate* unmanaged[Cdecl]<float, float, void*, float> vertical_filter, [NativeTypeName("stbir__support_callback *")] delegate* unmanaged[Cdecl]<float, void*, float> vertical_support);

        [DllImport("stb_image", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int stbir_set_pixel_subrect(STBIR_RESIZE* resize, int subx, int suby, int subw, int subh);

        [DllImport("stb_image", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int stbir_set_input_subrect(STBIR_RESIZE* resize, double s0, double t0, double s1, double t1);

        [DllImport("stb_image", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int stbir_set_output_pixel_subrect(STBIR_RESIZE* resize, int subx, int suby, int subw, int subh);

        [DllImport("stb_image", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int stbir_set_non_pm_alpha_speed_over_quality(STBIR_RESIZE* resize, int non_pma_alpha_speed_over_quality);

        [DllImport("stb_image", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int stbir_build_samplers(STBIR_RESIZE* resize);

        [DllImport("stb_image", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void stbir_free_samplers(STBIR_RESIZE* resize);

        [DllImport("stb_image", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int stbir_resize_extended(STBIR_RESIZE* resize);

        [DllImport("stb_image", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int stbir_build_samplers_with_splits(STBIR_RESIZE* resize, int try_splits);

        [DllImport("stb_image", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int stbir_resize_extended_split(STBIR_RESIZE* resize, int split_start, int split_count);
    }
}
#pragma warning restore CS0649
